name: AVR build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy avr-gcc
      uses: Alex079/setup-custom-tool@master
      with:
        archiveUrl: 'https://blog.zakkemble.net/download/avr-gcc-9.2.0-x64-mingw.zip'
        archiveGlob: '*/bin'
    - name: Build
      run: make -f .github/workflows/Makefile
